# Generated by Django 4.2.6 on 2024-07-11 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        db_column="dataset_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=128)),
                ("version", models.CharField(db_column="version", max_length=128)),
                (
                    "description",
                    models.CharField(db_column="description", max_length=128),
                ),
                ("time", models.CharField(db_column="time", max_length=128)),
                ("type", models.CharField(db_column="type", max_length=128)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dataset",
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        db_column="model_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=128)),
                ("version", models.CharField(db_column="version", max_length=128)),
                ("description", models.TextField(db_column="description")),
                ("url", models.URLField(db_column="url")),
                ("time", models.CharField(db_column="time", max_length=128)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "model",
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        db_column="node_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=128)),
                (
                    "description",
                    models.CharField(db_column="description", max_length=128),
                ),
            ],
            options={
                "db_table": "node",
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        db_column="scenario_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=128)),
            ],
            options={
                "db_table": "scenario",
            },
        ),
        migrations.CreateModel(
            name="ModelScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.ForeignKey(
                        db_column="model_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.model",
                    ),
                ),
                (
                    "scenario_id",
                    models.ForeignKey(
                        db_column="scenario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "model_scenario",
            },
        ),
        migrations.CreateModel(
            name="DatasetScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_id",
                    models.ForeignKey(
                        db_column="dataset_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.dataset",
                    ),
                ),
                (
                    "scenario_id",
                    models.ForeignKey(
                        db_column="scenario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "dataset_scenario",
            },
        ),
    ]
